/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check process liveness */
        get: operations["healthcheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check application readiness */
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List immutable demo scenarios */
        get: operations["listScenarios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a replay run */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current replay state */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}/control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Control replay state */
        post: operations["controlRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream replay telemetry and events */
        get: operations["streamRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events for a replay run */
        get: operations["listRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get event diagnosis and evidence */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a human decision */
        post: operations["decideEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate a preset operator account */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current operator identity */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{recordId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an auditable decision record */
        get: operations["getRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {unknown} */
            status: "ok" | "degraded";
            checks?: {
                [key: string]: string;
            };
        };
        Scenario: {
            id: string;
            name: string;
            description?: string | null;
            faultId: number;
            sampleCount: number;
            faultOnsetSample: number;
            /** @constant */
            sourceLabel: "Tennessee Eastman Process public simulation";
        };
        CreateRunRequest: {
            scenarioId: string;
            /**
             * @default 10
             * @enum {number}
             */
            speed: 1 | 5 | 10 | 20;
        };
        ReplayRun: {
            /** Format: uuid */
            id: string;
            scenarioId: string;
            /** @enum {unknown} */
            state: "ready" | "playing" | "paused" | "completed" | "failed";
            speed: number;
            currentSample: number;
            /** Format: date-time */
            createdAt: string;
        };
        RunControlRequest: {
            /** @enum {unknown} */
            action: "play" | "pause" | "restart" | "seek";
            sampleIndex?: number;
            /** @enum {number} */
            speed?: 1 | 5 | 10 | 20;
        };
        AnomalyEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            runId: string;
            sampleIndex: number;
            /** @enum {unknown} */
            severity: "warning" | "critical";
            /** @enum {unknown} */
            state: "open" | "confirmed" | "rejected" | "escalated";
            anomalyScore: number;
        };
        FaultCandidate: {
            faultId: number;
            label: string;
            probability: number;
        };
        EvidenceItem: {
            variableId: string;
            variableName: string;
            unit: string;
            contribution: number;
            /** @enum {unknown} */
            direction: "up" | "down" | "mixed";
            summary: string;
            values: number[];
        };
        Recommendation: {
            /** @enum {unknown} */
            mode: "template" | "llm_enhanced" | "degraded";
            risk: string;
            checks: string[];
            actions: string[];
            /** @constant */
            safetyBoundary: "Read-only advice. No automatic control write-back.";
        };
        EventDetail: components["schemas"]["AnomalyEvent"] & {
            /** @description First sample where the anomaly event was latched. */
            detectionSample: number;
            /** @description Sample used for the latest delayed candidate and evidence refresh. */
            diagnosisSample: number;
            /**
             * @description Pre-registered, label-independent delay after anomaly detection.
             * @constant
             */
            diagnosisDelaySamples: 20;
            /** @enum {unknown} */
            diagnosisState: "pending" | "provisional" | "updated";
            diagnosisAnomalyScore: number;
            /** @constant */
            anomalyLatched: true;
            initialCandidates: components["schemas"]["FaultCandidate"][];
            candidates: components["schemas"]["FaultCandidate"][];
            evidence: components["schemas"]["EvidenceItem"][];
            recommendation: components["schemas"]["Recommendation"];
            modelVersion: string;
            /** @constant */
            dataSourceDisclosure: "Public simulation data, not real Guizhou plant data.";
        };
        DecisionRequest: {
            /** @enum {unknown} */
            decision: "confirm" | "reject" | "escalate";
            /**
             * @default followed
             * @enum {unknown}
             */
            decisionMethod: "followed" | "partially_followed" | "overridden";
            note: string;
        };
        DecisionRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            eventId: string;
            /** @enum {unknown} */
            decision: "confirm" | "reject" | "escalate";
            operatorName: string;
            operatorRole?: string;
            note: string;
            /** Format: date-time */
            createdAt: string;
            modelVersion: string;
            traceId: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            username: string;
            /** @enum {unknown} */
            role: "operator" | "shift_lead";
            displayName: string;
            /** Format: date-time */
            expiresAt: string;
        };
        OperatorInfo: {
            username: string;
            /** @enum {unknown} */
            role: "operator" | "shift_lead";
            displayName: string;
        };
        Problem: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            traceId: string;
        };
    };
    responses: {
        /** @description Request could not be completed. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        RunId: string;
        EventId: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthcheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            400: components["responses"]["Problem"];
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependencies and demo data are ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            400: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    listScenarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available immutable demo scenarios. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scenario"][];
                };
            };
            400: components["responses"]["Problem"];
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Replay run created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayRun"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current replay state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayRun"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    controlRun: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunControlRequest"];
            };
        };
        responses: {
            /** @description Updated replay state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayRun"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    streamRun: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
            };
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream with telemetry, anomaly and heartbeat events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events detected for the run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyEvent"][];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Diagnosis, evidence and recommendation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    decideEvent: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Human decision and immutable record created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRecord"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Bearer token with operator identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated operator identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorInfo"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Auditable event decision record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRecord"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
}
